Controller
API Controller::api
object from abi class to call it function when need treat with in/out json files
Referenced by readJson, WriteJson.
vector<topology *> Controller::TopologyList
TopologyList act as memory of the device while hold the converted json files from reading.
Referenced by deleteTopology, findTopology, Querytopologies, QueryWhichDevicesIn, readJson, whichConnected, WriteJson.
Controller::Controller()
start the main program
void Controller::startprogram()
the start function of the program
References Deletetopology, getchoice, Querytopologies, QueryWhichDevicesIn, readJson, whichConnected, WriteJson.
string Controller::getchoice()
function to get the user choice and validate on input
its make it stick in while loop till chose correct choice string correct user choice
References valid.
Referenced by startprogram.
bool Controller::valid(string choice)
function to check the validation of user input if inout between 0 and 7 its correct else output wrong msg and request rfom user other valid input
choice the input from user true if valid coice false if invalid choice
Referenced by getchoice.
int Controller::getToplogyID()
Get the get Toplogy ID from user and check if exist or not by calling other function that iterate throw the tobology list.
int if found will return i (index of the topology) if not found will return -1
References findTopology.
Referenced by Deletetopology, getOutputJsonFileName, QueryWhichDevicesIn, whichConnected.
std::string Controller::getInputJsonFileName()
get json file name from user and validate on it by chick its alreay created or not and user doent enter empty ot non json file
string the file name.json
Referenced by getOutputJsonFileName, readJson.
int Controller::findTopology(string topologyID) const
general purose function to get topology index in memory
topologyID the string is of searched topology int if found will return i (index of the topology) if not found will return -1
References TopologyList.
Referenced by getToplogyID.
void Controller::readJson()
Read a topology from a given JSON file and store it in the memory. by calling api.readjson with the input name.
References api, getInputJsonFileName, API::ReadJson, TopologyList.
Referenced by startprogram.
void Controller::WriteJson()
Write a given topology from the memory to a JSON file by calling api.write with the input name and the topology.
References api, getOutputJsonFileName, TopologyList, API::writeToJSON.
Referenced by startprogram.
pair< string, int > Controller::getOutputJsonFileName()
Get the Output Json File Name object simple functionget the file name and topolgy id by ohter function and return a pair of them.
pair<string, int> <filename , topologyID>
References getInputJsonFileName, getToplogyID.
Referenced by WriteJson.
void Controller::Querytopologies()
Query about which topologies are currently in the memory printing all topologyes id from memory.
References TopologyList.
Referenced by startprogram.
void Controller::Deletetopology()
Delete a given topology from memory after take the topology name from user and validate on it.
References deleteTopology, getToplogyID.
Referenced by startprogram.
bool Controller::deleteTopology(int index)
delete specific location in topologylist
index index of deleted topology true if deleted successfully false and not found or any exception
References TopologyList.
Referenced by Deletetopology.
void Controller::QueryWhichDevicesIn()
printout the devices connected in some topologies Query about which devices are in a given topology
References getToplogyID, TopologyList.
Referenced by startprogram.
void Controller::whichConnected()
Query about which devices are connected to a given netlist node in a given topology.
References getToplogyID, TopologyList.
Referenced by startprogram.