Device
string Device::id
id of the device
Referenced by get_id, setID.
map<string, string> Device::netList
map contain devices connected to this device 3 terminals or 2 terminals
Referenced by Device, get_netList, ThreeTerminal::getDrain, ThreeTerminal::getGate, ThreeTerminal::getSrc, TwoTerminal::getT1, TwoTerminal::getT2, set_netList, ThreeTerminal::setDrain, ThreeTerminal::setGate, ThreeTerminal::setSrc, TwoTerminal::setT1, TwoTerminal::setT2.
float Device::defaulval
the defalt and min and max value that can be connected to component
Referenced by get_Default, set_Default.
float Device::max
float Device::min
string Device::type
string hold the type of the Device
Referenced by get_type, set_type.
Device::Device(string id, map< string, string > netList, float def, float max, float min)
Construct a new Device object.
id the id of the device netList the list of connected devices to the device def default valude from this device max max valude from this device min min valude from this device
References netList, set_Default, set_Max, set_Min, set_netList, setID.
Device::Device()
default Construct a new Device object
References set_Default, set_Max, set_Min, set_type.
void Device::setID(string id)
set the ID of the Device
id new ID of device
References id.
Referenced by Device.
void Device::set_Default(float def)
Set the Default object.
def new default value of device
References defaulval.
Referenced by Device.
void Device::set_netList(map< string, string > netList)
Set the netList object.
netList new netList of device
References netList.
Referenced by Device.
void Device::set_Max(float max)
Set the Max object.
max new max value of device
Referenced by Device.
void Device::set_Min(float min)
Set the Min object.
min new min value of device
Referenced by Device.
void Device::set_type(string name)
Set the type object.
name new type
References type.
Referenced by Device, Nmos::Nmos, Pmos::Pmos, Resistance::Resistance.
string Device::get_type()
Get the type object.
string
References type.
Referenced by API::ConvertDeviceToJson, Resistance::Print_Device.
float Device::get_Default()
Get the Default object.
float
References defaulval.
Referenced by API::ConvertDeviceToJson, Print_Device.
map< string, string > Device::get_netList()
Get the netList object.
map<string, string>
References netList.
Referenced by API::ConvertDeviceToJson.
float Device::get_max()
Get the max object.
float
Referenced by API::ConvertDeviceToJson, Print_Device.
float Device::get_min()
Get the min object.
float
Referenced by API::ConvertDeviceToJson, Print_Device.
string Device::get_id()
Get the id object.
string
References id.
Referenced by API::ConvertDeviceToJson, Nmos::Print_Device, Pmos::Print_Device.
void Device::Print_Device()
print the general device info
References get_Default, get_max, get_min.
Referenced by Nmos::Print_Device, Pmos::Print_Device, Resistance::Print_Device.
Device::~Device()