API
API::API()
topology * API::ReadJson(string FileName)
function used to create object from json file and check its empty or not and return pointer no null if object empty
FileName filename of json file prechecked on his validation topology * the topology object formed from json file (filename)
References createTopology.
Referenced by Controller::readJson.
topology * API::createTopology(json jsonObject)
Create a Topology object from json object passed to it by devide it to smaller task , each task create one list.
jsonObject json object from file name passed to readjson topology * the topology object formed from json file (filename) and adding its id
References createListOfDevices.
Referenced by ReadJson.
vector< Device * > API::createListOfDevices(json jsonObject)
Create a List Of Devices object, by looping throught the lists exist in file and give each device to procude it.
jsonObject json object from file name passed to readjson vector<Device*> vector of pointers of devices in list
References createDevice.
Referenced by createTopology.
Device * API::createDevice(const json &DeviceJson)
Create a Device object given from createListOfDevices by detect Device type and all suitanle function for it's creation.
DeviceJson the device passed as json object Device* pointer to Device object
References createNmos, createPmos, createResistor.
Referenced by createListOfDevices.
Device * API::createNmos(const json &DeviceJson)
Create a Nmos object , called if the device type is Nmos.
DeviceJson the Nmos passed as json object, with its specifications Device* pointer to Device object
Referenced by createDevice.
Device * API::createPmos(const json &DeviceJson)
Create a Nmos object , called if the device type is Pmos.
DeviceJson the Pmos passed as json object, with its specifications Device* pointer to Device object
Referenced by createDevice.
Device * API::createResistor(const json &DeviceJson)
Create a Resistor object , called if the device type is Resistor.
DeviceJson the Resistor passed as json object, with its specifications Device* pointer to Device object
Referenced by createDevice.
bool API::writeToJSON(string filename, const topology *Topology)
function used to convert topology in memory to json file in a given json file name
filename name of the file program will write on it Topology the topology which will be printed in as json object true is every thing done correctly false if throw any exepection from reading file or write on it
References ConvertTopologyTojson.
Referenced by Controller::WriteJson.
json API::ConvertTopologyTojson(const topology *topo)
convert the topology object to json object by divide it into smaller tasks. each task is convert Device to separte json object
topo json file to the topology program will convert json
References ConvertDevicesToJson, topology::getDevices, topology::getID.
Referenced by writeToJSON.
json API::ConvertDevicesToJson(const vector< Device * > &Devices)
function usedto separte all devices in given topology into json files per device
Deviceslist of devices want to convert json json file to the list of deviecs converted
References ConvertDeviceToJson.
Referenced by ConvertTopologyTojson.
json API::ConvertDeviceToJson(Device *comp)
function convert device object into json onject
comp the object of device want to convert it json json file of that device
References Device::get_Default, Device::get_id, Device::get_max, Device::get_min, Device::get_netList, Device::get_type.
Referenced by ConvertDevicesToJson.
API::~API()
Destroy the API object when end.