topology
string topology::id
id of the topology
vector<Device*> topology::Devices
vector of Devices in this topology
topology::topology(string id)
Construct a new empty topology object.
id the id of this object
topology::topology(string id, const vector< Device * > &Devices)
Construct a new topology object given its id and its set of Devices.
id the id of this object Devices set of Devices
References setDevices.
void topology::setDevices(const vector< Device * > &Devices)
Set the vector of Devices.
Devices
Referenced by topology.
void topology::setId(string id)
Set the Id object.
id
string topology::getID() const
getID object
string
Referenced by API::ConvertTopologyTojson.
vector< Device * > topology::getDevices() const
Get the Devices object.
vector<Device*>
Referenced by API::ConvertTopologyTojson.
vector< Device * > topology::getConnectedDevices(string netListNodeID) const
Get the Connected Devices object.
netListNodeID the net list of searched devices vector<Device*> the connected devices
References ISconnectedNetList.
bool topology::ISconnectedNetList(string netListNodeID, map< string, string > netList) const
netListNodeID Device id you want to search for netList the vector of devices that search on it true false
Referenced by getConnectedDevices.
topology::~topology()
Destroy the topology object.